container:
  image: cirrusci/flutter:base

task:
  name: tool_tests-linux
  container:
    cpu: 4
    memory: 8G
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"
    PUB_ENVIRONMENT: "flutter_bot:flutter_install"

  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: grep -r --include=pubspec.yaml 'PUBSPEC CHECKSUM' "$CIRRUS_WORKING_DIR"

  git_fetch_script: git fetch origin
  flutter_version_script: ./bin/flutter --version
  flutter_disable_analytics_script: ./bin/flutter config --no-analytics
  flutter_update_packages_script: ./bin/flutter update-packages
  fetch_fetch_master_script: git fetch origin master

task:
  name: tool_tests-windows
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
    PATH: "$CIRRUS_WORKING_DIR\\bin;$CIRRUS_WORKING_DIR\\bin\\cache\\dart-sdk\\bin;$PATH"
    PUB_ENVIRONMENT: "flutter_bot:flutter_install"
    
  pub_cache:
    folder: $APPDATA\Pub\Cache
    fingerprint_script:
      - ps:  Get-ChildItem -Path "$Env:CIRRUS_WORKING_DIR" pubspec.yaml -Recurse | Select-String -Pattern "PUBSPEC CHECKSUM" -SimpleMatch

  git_fetch_script: git fetch origin
  flutter_version_script: bin\flutter.bat --version
  flutter_disable_analytics_script:
    - ps: |
      filter timestamp {"$(Get-Date -Format o): $_"}
      bin\flutter.bat config --no-analytics | timestamp
  flutter_update_packages_script: bin\flutter.bat update-packages
  fetch_fetch_master_script: git fetch origin master
