container:
  image: cirrusci/flutter:base

task:
  name: tool_tests-linux
  container:
    cpu: 4
    memory: 8G
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"

  git_fetch_script: git fetch origin
  flutter_version_script: ./bin/flutter --version
  flutter_disable_analytics_script: ./bin/flutter config --no-analytics
  flutter_update_packages_script: ./bin/flutter update-packages
  fetch_fetch_master_script: git fetch origin master

task:
  name: tool_tests-windows
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
    
  git_fetch_script: git fetch origin
  flutter_version_script: bin\flutter.bat --version
  flutter_disable_analytics_script: bin\flutter.bat config --no-analytics
  flutter_update_packages_script: bin\flutter.bat update-packages
  fetch_fetch_master_script: git fetch origin master

task:
  name: tool_tests-windows-8g-ram
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
    memory: 8G
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
    
  git_fetch_script: git fetch origin
  flutter_version_script: bin\flutter.bat --version
  flutter_disable_analytics_script: bin\flutter.bat config --no-analytics
  flutter_update_packages_script: bin\flutter.bat update-packages
  fetch_fetch_master_script: git fetch origin master

task:
  name: tool_tests-windows-16g-ram
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
    memory: 16G
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
    
  git_fetch_script: git fetch origin
  flutter_version_script: bin\flutter.bat --version
  flutter_disable_analytics_script: bin\flutter.bat config --no-analytics
  flutter_update_packages_script: bin\flutter.bat update-packages
  fetch_fetch_master_script: git fetch origin master

task:
  name: tool_tests-windows-8-core-16gb-ram
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 8
    memory: 16G
  env:
    SHARD: tool_tests
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
    
  git_fetch_script: git fetch origin
  flutter_version_script: bin\flutter.bat --version
  flutter_disable_analytics_script: bin\flutter.bat config --no-analytics
  flutter_update_packages_script: bin\flutter.bat update-packages
  fetch_fetch_master_script: git fetch origin master
