container:
  image: cirrusci/flutter:base

task:
  env:
    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"

  git_fetch_script: git fetch origin
  setup_script: |
    echo "SDK directory is: $PWD"
    ./bin/flutter --version

    # disable analytics on the bots and download Flutter dependencies
    ./bin/flutter config --no-analytics

    # run pub get in all the repo packages
    ./bin/flutter update-packages

    git fetch origin master
  matrix:
    - name: tool_tests-linux
      env:
        SHARD: tool_tests
      test_script:
        - dart ./dev/bots/test.dart
      container:
        cpu: 4
        memory: 8G

task:
  env:
    SHARD: tests
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
  env:
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
  git_fetch_script: git fetch origin
  setup_script:
    - bin\flutter.bat config --no-analytics
    - bin\flutter.bat update-packages
    - git fetch origin master
  test_all_script:
    - bin\cache\dart-sdk\bin\dart.exe -c dev\bots\test.dart
  matrix:
    - name: tool_tests-windows
      env:
        SHARD: tool_tests
